# Local Cargo.toml overlay for development in monorepo
# These patches are intentionally ignored in .pubignore for publishing to pub.dev
[patch."https://github.com/payjoin/rust-payjoin.git"]
payjoin-ffi = { path = ".." }
payjoin = { path = "../../payjoin" }

[patch.crates-io]
payjoin = { path = "../../payjoin" }
payjoin-mailroom = { path = "../../payjoin-mailroom" }
payjoin-test-utils = { path = "../../payjoin-test-utils" }
